#!/bin/bash

# CLI tools
brew install ack
brew install coreutils
brew install diff-so-fancy
brew install git
brew install opam
brew install trash
brew install tree
brew install wget
brew install z

# neovim
brew install lua
brew install neovim
brew install tree-sitter
brew install ripgrep
brew install fd

# zsh plugins
brew install zsh-history-substring-search

# fonts
brew tap caskroom/fonts
brew cask install font-source-code-pro
brew cask install font-sauce-code-pro-nerd-font
