#!/bin/bash

# CLI tools
brew install coreutils
brew install ack
brew install curl
brew install diff-so-fancy
brew install gawk
brew install git
brew install grep
brew install jq
brew install opam
brew install sed
brew install trash
brew install tree
brew install wget
brew install z
brew install asdf # deps: coreutils curl git

# neovim
brew install lua
brew install neovim
brew install ripgrep
brew install fd

# zsh plugins
brew install zsh-history-substring-search

# fonts
brew tap homebrew/cask-fonts
brew install --cask font-source-code-pro
brew install --cask font-sauce-code-pro-nerd-font
