#!/bin/bash
# setup initial programs that can't be installed via brew reliably


# Homebrew
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

# Node Version Manager
# https://github.com/creationix/nvm

# iterm theme
# https://gist.github.com/luan/6362811

# Oh-My-ZSH
sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
# remove default zshrc file so symlink will work correctly
mv .zshrc _default_zshrc
