#!/bin/bash

# Manually Symlink Files below

ln -s ~/Dotfiles/ackrc ~/.ackrc
ln -s ~/Dotfiles/gitconfig ~/.gitconfig
ln -s ~/Dotfiles/githelpers ~/.githelpers
ln -s ~/Dotfiles/gitignore_global ~/.gitignore_global
ln -s ~/Dotfiles/vim ~/.vim
ln -s ~/Dotfiles/vimrc ~/.vimrc
ln -s ~/Dotfiles/zshrc ~/.zshrc
ln -s ~/Dotfiles/npmrc ~/.npmrc

# install Vundle plugin manageer
#git clone https://github.com/gmarik/Vundle.vim.git ~/.vim/bundle/Vundle.vim

while true; do
    read -p "Would you like to run NPM install script? " yn
    case $yn in
        [Yy]* ) ~/Dotfiles/npm_installs; break;;
        [Nn]* ) exit;;
         *    ) echo "Please answer yes or no.";;
    esac
done


while true; do
    read -p "Would you like to run brew install script? " yn
    case $yn in
        [Yy]* ) ~/Dotfiles/brew_installs; break;;
        [Nn]* ) exit;;
         *    ) echo "Please answer yes or no.";;
    esac
done

