#!/bin/bash

# Manually Symlink Files below

ln -s ~/Dotfiles/ackrc ~/.ackrc
ln -s ~/Dotfiles/gitconfig ~/.gitconfig
ln -s ~/Dotfiles/githelpers ~/.githelpers
ln -s ~/Dotfiles/gitignore_global ~/.gitignore_global
ln -s ~/Dotfiles/vim ~/.vim
ln -s ~/Dotfiles/spacemacs ~/.spacemacs
ln -s ~/Dotfiles/vimrc ~/.vimrc
ln -s ~/Dotfiles/zshrc ~/.zshrc

# install Vundle plugin manageer
#git clone https://github.com/gmarik/Vundle.vim.git ~/.vim/bundle/Vundle.vim
