#!/bin/bash

# Manually Symlink Files below

ln -s ~/Dotfiles/ackrc ~/.ackrc
ln -s ~/Dotfiles/gitconfig ~/.gitconfig
ln -s ~/Dotfiles/githelpers ~/.githelpers
ln -s ~/Dotfiles/gitignore_global ~/.gitignore_global
ln -s ~/Dotfiles/vim ~/.vim
ln -s ~/Dotfiles/vimrc ~/.vimrc
ln -s ~/Dotfiles/zshrc ~/.zshrc
