#!/bin/bash

npm install -g chimp
npm install -g karma-cli
npm install -g react-native-cli
npm install -g tern
npm install -g create-react-app
#sudo npm install -g elm-oracle
#sudo npm install -g apphub
