#!/bin/bash

sudo npm install -g eslint
sudo npm install -g eslint-plugin-react
sudo npm install -g eslint-config-airbnb
sudo npm install -g sass
sudo npm install -g chimp
sudo npm install -g karma-cli
sudo npm install -g react-native-cli
sudo npm install -g tern
sudo npm install -g apphub
